services:
  searxng:
    image: ${SEARXNG_IMAGE:-searxng/searxng:latest}
    container_name: searxng
    restart: unless-stopped
    ports:
      - ${SEARXNG_PORT:-8080}:8080
    volumes:
      - ./data/settings.yml:/etc/searxng/settings.yml:ro
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-http://localhost:8080}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
